package bg.sofia.uni.fmi.mjt.boardgames;

import bg.sofia.uni.fmi.mjt.boardgames.recommender.Recommender;

public class Main {
    public static void main(String[] args) {
        BoardGame original = BoardGame.of("17301;5;8;2;Star Wars: Attack of the Clones Card Game;45;Card Game,Movies / TV / Radio theme,Science Fiction;Press Your Luck,Set Collection;The game is based on Reiner Knizia's Circus Flohcati but changes the special action cards and adds missions to be completed. It is played over three rounds...Re-implements:..    Circus Flohcati.....");

        BoardGame game1 = BoardGame.of("931;4;8;2;Captain Future;45;Movies / TV / Radio theme,Science Fiction;Area Control / Area Influence;.A Mysterious Universe. Silver and glass rockets jet around the galaxy. Other planets are now being populated by courageous scientists and spacemen. Captain Future with his team of the space pirate GRAG, Otto the Android, and Simon Wright, the living brain, dive into the fight against foreign invaders...Object of the game is to occupy as many spaces on the planets as possible...Bits: 1 board, 66 space cards, (space and event cards) 170 spaceships, 1 secret stone, rules...Once  all spaces on a planet are occupied, the planet is conquered...Whoever has the majority on a planet can play a card to kick a foreign ship off the planet...A player without a majority, but at least a space on the planet can conquer a spaceship on the planet with two cards...A player without a spaceship on the planet can conquer with 3 cards. If no players have a definite majority, then all attacks require two or three cards...The game ends when a player plays his last ship. Each other player may play one more time before the game ends.   Each player gets as many points as he has spaceships on planets. Whoever completely controls a planet gets 5 for a big planet, 4 for an average planet, and 3 for a moon...For other planets a player with a majority receives one extra point...Whoever has the most points wins the game...Origo seems to be a reworking of this game..");
        BoardGame game2 = BoardGame.of("58863;4;8;2;Star Wars: Angriff der Klonkrieger;45;Movies / TV / Radio theme,Science Fiction;Co-operative Play;Game description from the publisher:..Obi-Wan Kenobi, Anakin Skywalker and Padm&eacute  Amidala have fallen into an ambush on Geonosis. Many Jedi have arrived to rescue them, including Mace Windu and Kit Fisto. But suddenly the Jedi are surrounded by an army of battle droids and super battle droids led by Count Dooku...In Star Wars: Angriff der Klonkrieger , you'll try to use your Jedi dice to hold your position and fend off the onslaught of droids. Will you be able to hold out until Yoda arrives with the clone army?.. Game Mechanics..Each player has a set of dice, and together the players must fend off special threats and new droids that are arriving every round. Every player throws a die each round and then they are allocated...The special threats need particular dice values (for example, four threes) which can be collected over multiple rounds. Failing to counter a special threat may lead to additional droids being put on the board, or immediate defeat...For attacking droids just the sum of the dice values is used. This is the only part of the game where the player figurines must move on the board to get into attack range...The game ends after a fixed number of rounds, or if the players fail to counter a special threat...");
        BoardGame game3 = BoardGame.of("1091;6;8;2;Rook;45;Card Game;Auction/Bidding,Card Drafting,Hand Management,Partnerships,Trick-taking;Rook is a trump-based trick-taking game played with a deck of Rook playing cards. It was first sold in 1906 by Parker Brothers.  The Rook deck is similar to a standard deck of cards, but has only numbers from 1-14 in four colors (no face cards or card suits (spades, etc.))...The standard game is a 4-player partnership game with the 1's, 2's, 3's, and 4's removed for a deck of 41 cards (with the Rook card).  Each hand, players bid for Trump, and then the partnership that won the bid must make the amount of points bid in the hand.  Play of each trick is similar to Whist games like Bridge. The card led must be followed by a card of the same color.  A player may play a trump color if they have none of the color led.  The highest card of the color led wins the trick, unless the trick is trumped, and then the highest trump wins the trick.  The Rook card can be played at any time, and always wins the trick.  Unlike Whist or Bridge, the amount of tricks is not important, but certain count cards (5's, 10's, 14's, and the Rook card) taken in tricks are worth points, which is how the game is scored...The standard game is 4-player, but there are variants for 2-player and 3-player in the rules, and there also are many variations and house rules used in play...Rook has also been referred to as Missionary Poker.  The Rook deck, with no-face cards or suits from a standard deck of cards, has often been a card game played by religious groups who object to using a standard deck of cards...");
        BoardGame game4 = BoardGame.of("3541;4;8;2;Won Over;45;Card Game;Trick-taking;The Finish card is placed at the end of the twelve Track cards. Players place their pawns at the opposite end of the finish. Players cut cards to determine the first dealer and the trump suit. In the four-player version of the game all the cards are dealt. (There are rule variations for two and three players.) The player to the left of the dealer plays the first card and the others, in turn, must follow suit of they can. The highest card wins the trick and advances one&rsquo s pawn down the track. The color of the card on which the lead pawn rests is always trump. No players may share the same space. If the next space is occupied, the player advances to the next unoccupied space...In addition, the deck contains two Suit Yourself cards and four Sidetracked cards. The Suit Yourself cards are ubertrump and the players must follow trump if any trick is lead with it. Any player who takes a trick containing a Sidetracked card must move off the track and but that player comes back to the track on the next trick that player wins...The first player to get one&rsquo s pawn to the Finish card is the winner...");

        BoardGame game5 = BoardGame.of("2108;5;8;2;Cows Can't Dance (but they like to be asked);45;Card Game;Set Collection;In this outrageous card game, cows and bulls dance...but only by invitation. Pair a cow card with a bull card and earn extra points. Match dancer cards of the same suit or use your Madame Fifi card to cut in for a dance lesson. Earn points for each pair on your dance floor. The player with the most points wins...");
        BoardGame game6 = BoardGame.of("1089;6;8;2;Phase 10;45;Card Game;Set Collection;A rummy-type card game where players compete to be the first to finish completing all ten phases.  Phases include collecting runs of numbers, collecting certain number of a given color cards, etc.  The first player to finish completing the 10th phase wins.  In case of ties, the player with the fewest number of points wins...Contents:..     Reference Cards (2).     Deck of 108 Cards:.         24 x Red Cards (2 x 1-12).         24 x Blue Cards (2 x 1-12).         24 x Green Cards (2 x 1-12).         24 x Yellow Cards (2 x 1-12).         4 x Skip Cards.         8 x Wild Cards (2 x 4 Colors).    .     Instructions.....");
       // BoardGame game7 =

        System.out.println(original.getDistanceTo(game1));
        System.out.println(original.getDistanceTo(game2));
        System.out.println(original.getDistanceTo(game3));
        System.out.println(original.getDistanceTo(game4));
        System.out.println(original.getDistanceTo(game5));
        System.out.println(original.getDistanceTo(game6));
    }
}
